name: build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.actor == 'dependabot[bot]' }}

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: localhost/feedbin:edge
          labels: ${{ steps.docker-metadata.outputs.labels }}

      - name: Force Rootful Podman with Native OverlayFS
        run: |-
          printf '%s\n' '#!/bin/sh' 'exec /usr/bin/sudo -n -- /usr/bin/podman "$@"' | sudo tee /usr/local/bin/podman
          sudo chmod a+x /usr/local/bin/podman

      - name: Build
        run: podman build --cap-add CAP_SYS_ADMIN --volume /var/run/docker.sock:/var/run/docker.sock $(echo "$tags" | xargs -n 1 -r -- echo --tag) -- .
        env:
          tags: ${{ steps.docker-metadata.outputs.tags }}

      - name: Push
        if: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
        run: echo "$tags" | xargs -n 1 -r -- podman push --authfile ~/.docker/config.json --
        env:
          tags: ${{ steps.docker-metadata.outputs.tags }}
